/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner API
 * API for managing trips
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TripUpdate
 */
export interface TripUpdate {
    /**
     * 
     * @type {string}
     * @memberof TripUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TripUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TripUpdate
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TripUpdate
     */
    endDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof TripUpdate
     */
    participants?: number;
    /**
     * 
     * @type {string}
     * @memberof TripUpdate
     */
    imageUrl?: string | null;
}

/**
 * Check if a given object implements the TripUpdate interface.
 */
export function instanceOfTripUpdate(value: object): value is TripUpdate {
    return true;
}

export function TripUpdateFromJSON(json: any): TripUpdate {
    return TripUpdateFromJSONTyped(json, false);
}

export function TripUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'participants': json['participants'] == null ? undefined : json['participants'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
    };
}

export function TripUpdateToJSON(json: any): TripUpdate {
    return TripUpdateToJSONTyped(json, false);
}

export function TripUpdateToJSONTyped(value?: TripUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'participants': value['participants'],
        'imageUrl': value['imageUrl'],
    };
}

