/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner API
 * API for managing trips
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Trip
 */
export interface Trip {
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Trip
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Trip
     */
    endDate: Date;
    /**
     * 
     * @type {number}
     * @memberof Trip
     */
    participants: number;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Trip
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Trip
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Trip interface.
 */
export function instanceOfTrip(value: object): value is Trip {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('participants' in value) || value['participants'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TripFromJSON(json: any): Trip {
    return TripFromJSONTyped(json, false);
}

export function TripFromJSONTyped(json: any, ignoreDiscriminator: boolean): Trip {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'participants': json['participants'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function TripToJSON(json: any): Trip {
    return TripToJSONTyped(json, false);
}

export function TripToJSONTyped(value?: Trip | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'startDate': ((value['startDate']).toISOString()),
        'endDate': ((value['endDate']).toISOString()),
        'participants': value['participants'],
        'imageUrl': value['imageUrl'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

